defaults: &defaults
  oauth:
    redirect_uri: 'http://dashboard.predicsis.dev/oauth/callback'
    client_id: 'f4d92fb8928472f6a228beaeef08531b38ab27352a34ab3bfea986e9a78e4094'
    client_secret: '5254df37c4c76eee7d175ab3c20045f6af5670d9c3bdb86f40618f8559b2796c'

development:
  <<: *defaults
  server_endpoint:
    api: 'http://localhost:3001'
    identity: 'http://localhost:3002'
  secret_key_base: b3a0cc089b58ffbbf032e15aa174e26de702f438a01e597da94c617dde0f893cad6894a494a40fba3cef644bfab163fccc0d7ba26768715ff28db98ef7af5fd3

test:
  <<: *defaults
  server_endpoint:
    api: 'http://localhost:3001'
    identity: 'http://localhost:3002'
  secret_key_base: b3a0cc089b58ffbbf032e15aa174e26de702f438a01e597da94c617dde0f893cad6894a494a40fba3cef644bfab163fccc0d7ba26768715ff28db98ef7af5fd3

staging:
  <<: *defaults
  server_endpoint:
    api: 'https://api.stagedicsis.net'
    identity: 'https://id.stagedicsis.net'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  oauth:
    redirect_uri: 'https://dashboard.stagedicsis.net/oauth/callback'
    client_id: 'f4d92fb8928472f6a228beaeef08531b38ab27352a34ab3bfea986e9a78e4094'
    client_secret: '2695e2d08bac5be4072ac29f48f7b5d0b68746e1aaa3ee8503335a534fb1761b'

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>